### ISSUE TITLE
Add a floor view

### ISSUE THREAD

**Issue by JonasDju** [JonasDju/HospiTool#24]
### Motivation
The current solution supports multiple wards that have a floor assigned to them. However, this information is not used anywhere in the visualization. It would be nice to have a dedicated 'Floor View' that allows the user to quickly get an overview of the different floors of the hospital including the wards on each floor and their utilization.

### Screenshots
Prototype coming soon.

**Comment by Jojo200401** [comment]
Add translations afterwards.
