### ISSUE TITLE
Finalize the patient intake process

### ISSUE THREAD

**Issue by FlyingJannis** [JonasDju/HospiTool#42]
We want to finalize the patient input process and implement the feedback of the group:

- [x] **Feature:** Only allow ward-specific discharge dates (e.g. some stations can only discharge patients on specific days of the week)
- [x] **Visual:** Make it visual clear for the user, which days are possible for discharge

- [x] **Feature:** Give the user a selection of common stay durations to make the selection of nights to stay faster
- [x] **Visual:** Regroup or redesign the layout of the form, such that it becomes clear for the user what has to be filled out.
- [ ] Input: Remove input for discharge time, set to default 12:00 in backend post handling

- [x] **Optional:** Streamline the intake process

- [x] **Translation:** Update/Add translations in `ycms/locale/de/LC_MESSAGES/django.po`

**Comment by matthisfranzgrote** [comment]
Make ward selection mandatory
